name: Docker Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ fromJSON(steps.meta.outputs.json).tags[1] }}

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    strategy:
      matrix:
        architecture: [amd64, arm64]

    steps:
      - uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/blazekill/heygen
          # generate Docker tags based on the following events/attributes
          tags: |
            type=sha,prefix={{branch}}-
            type=raw,value=latest

      - name: Build version
        id: version
        uses: actions/github-script@v6
        env:
          TAG: ${{ fromJSON(steps.meta.outputs.json).tags[1] }}
        with:
          result-encoding: string
          script: |
            const version = process.env.TAG.split(':')[1].trim()
            core.info(`Build version : ${version}`)
            return version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}-${{ matrix.architecture }}
          labels: ${{ steps.meta.outputs.labels }}-${{ matrix.architecture }}
          platforms: linux/${{ matrix.architecture }}