name: Heygen Integration Test

on:
  workflow_dispatch:
    inputs:
      job_time:
        description: 'Time it takes to complete each job at backend'
        required: false
        default: '3000'
        type: number

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn install
        working-directory: ./heygen-cli
      - run: yarn start
        working-directory: ./heygen-cli